### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Enuzo** [rikschennink/short-and-sweet#2] opened 2020-09-07 08:59 UTC
I keep getting this issue after importing the module:
`import shortAndSweet from 'short-and-sweet'`
Could not find a declaration file for module 'short-and-sweet'. '/path/short-and-sweet/dist/short-and-sweet.module.js' implicitly has an 'any' type.
  Try `npm install @types/short-and-sweet` if it exists or add a new declaration (.d.ts) file containing `declare module 'short-and-sweet';`

**Comment by rikschennink** [comment] 2020-09-07 10:07
There are no TypeScript definitions for short and sweet so TypeScript is throwing this error. Feel free to create a .d.ts file or check if @types has one.

**Comment by Enuzo** [comment] 2020-09-07 13:34
I created a short-and-sweet.d.ts file in the short-and-sweet folder with the following information:
`declare module 'short-and-sweet';`
But still doesn't work. Am I doing it wrong? I'm new to using this stuff. Thanks for your response.

**Comment by rikschennink** [comment] 2020-09-07 14:13
I don’t know this is TypeScript specific, I’ll close the issue as it’s not related to the lib and I currently don’t have time to add a .d.ts file myself.

**Closed as completed by rikschennink** 2020-09-07 14:13 UTC

**Comment by Enuzo** [comment] 2020-09-07 15:01
So, how do you get your lib to work with webpack-based projects? I don't care about typescript either. It's just about getting the lib to work. After installing with npm as instructed, I just get this issue:
```
news.js:1 Uncaught Error: Cannot find module 'short-and-sweet'
    at webpackMissingModule (news.js:1)
    at Module../js/news.js (news.js:1)
    at __webpack_require__ (bootstrap:19)
    at Module../js/app.js (app.js:1)
....


```

**Comment by rikschennink** [comment] 2020-09-07 17:36
I don't know, but this works as intended: https://codesandbox.io/s/short-and-sweet-demo-yf8gn?file=/src/index.js
